names=assert_nothing_raised
visibility=public
kind=defined

--- assert_nothing_raised(message = "") { ... }
--- assert_nothing_raised(klass1, klass2, ..., message = "") { ... }

ブロックを実行して例外が起きなければパスします。

ブロックを実行して発生した例外が klass1, klass2, ..., のいずれかのクラスの
インスタンスである場合は、assert は失敗扱いとなり、Test::Unit::AssertionFailedError
を投げます。そうでない場合は、エラー扱いとなり発生した例外を再び投げます。

@param klassX 例外クラスを指定します。

@param message assert が失敗した時に表示するメッセージを文字列で指定し
               ます。指定しなかった場合は表示しません。

@raise MiniTest::Assertion assert が失敗した時に発生します。

